name: Update Activity
on:
  schedule:
    - cron: '0 * * * *' # Actualiza cada hora
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update activity
        uses: crazy-max/ghaction-github-actions@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
